using namespace System.Management.Automation.Language
#PowerShell to JavaScript transpiler used by Convert-AzCmplyToWeb.ps1. Walks the PowerShell AST and emits JavaScript that
#runs on the runtime in site/js/runtime. Anything it does not support stops the conversion with the file and line, so
#the web variant never silently differs from the PowerShell source.

class TranspileError : System.Exception {
    TranspileError([string]$message) : base($message) {}
}

class JsFrame {
    [hashtable]$Typed = @{}
    [int]$LoopDepth = 0
    [bool]$InValueBlock = $false
    [string]$Out = 'O'
}

class PsToJs {
    [System.Text.StringBuilder]$Out
    [int]$Indent = 0
    [string]$SourceName        #path relative to the repository, e.g. Analyze/tests/06-Storage.ps1
    [string]$VirtualPath       #path in the runtime file system, e.g. /app/Analyze/tests/06-Storage.ps1
    [string]$VirtualRoot       #its folder: the value of $PSScriptRoot
    [int]$TempCounter = 0
    [System.Collections.Generic.Stack[JsFrame]]$Frames
    [System.Collections.Generic.HashSet[string]]$KnownCommands
    [System.Collections.Generic.HashSet[string]]$UsedCommands

    static [string[]]$RuntimeCmdlets = @(
        'ForEach-Object', 'Where-Object', 'Sort-Object', 'Group-Object', 'Select-Object', 'Measure-Object', 'ConvertTo-Json',
        'ConvertFrom-Json', 'ConvertTo-Csv', 'Join-Path', 'Split-Path', 'Resolve-Path', 'Test-Path', 'Get-ChildItem', 'Get-Content',
        'Set-Content', 'New-Item', 'Remove-Item', 'Expand-Archive', 'Get-Location', 'Get-Command', 'Write-Host', 'Write-Warning',
        'Write-Verbose', 'Write-Debug', 'Write-Information', 'Write-Progress', 'Write-Output', 'Write-Error', 'Out-Null', 'Out-String',
        'Start-Sleep', 'Get-Date', 'Set-StrictMode', 'Set-Location',
        '%', 'foreach', '?', 'where', 'sort', 'group', 'select', 'measure', 'gci', 'ls', 'dir', 'gc', 'cat', 'echo', 'write', 'rm', 'del',
        'ni', 'pwd', 'gl', 'sleep', 'rvpa', 'gcm'
    )

    #automatic variables that have no meaning in the browser runtime; using one stops the conversion
    static [string[]]$UnsupportedVariables = @('MyInvocation', 'PSBoundParameters', 'PSCmdlet', 'Error', 'LASTEXITCODE', 'Host', 'HOME', 'PID', 'this', 'foreach', 'switch', 'StackTrace', 'PSDefaultParameterValues', 'OFS', 'input')

    PsToJs([System.Collections.Generic.HashSet[string]]$knownCommands) {
        $this.Frames = [System.Collections.Generic.Stack[JsFrame]]::new()
        $this.KnownCommands = $knownCommands
        $this.UsedCommands = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    }

    #region output helpers

    [void] Line([string]$text) {
        [void]$this.Out.Append(' ' * (4 * $this.Indent)).Append($text).Append("`n")
    }

    [string] Tmp([string]$prefix) {
        $this.TempCounter++
        return "$prefix$($this.TempCounter)"
    }

    [void] Fail([Ast]$ast, [string]$message) {
        throw [TranspileError]::new("$($this.SourceName):$($ast.Extent.StartLineNumber): $message`n    $($ast.Extent.Text.Split("`n")[0].Trim())")
    }

    [JsFrame] Frame() { return $this.Frames.Peek() }

    static [string] Q([string]$s) {
        if ($null -eq $s) { return '""' }
        $t = $s.Replace('\', '\\').Replace('"', '\"').Replace("`n", '\n').Replace("`r", '\r').Replace("`t", '\t')
        $t = [regex]::Replace($t, '[\x00-\x08\x0B\x0C\x0E-\x1F\u2028\u2029]', { param($m) '\u{0:x4}' -f [int][char]$m.Value })
        return '"' + $t + '"'
    }

    static [string] Num([object]$v) {
        if ($v -is [double] -or $v -is [single]) {
            if ([double]::IsPositiveInfinity($v)) { return 'Infinity' }
            if ([double]::IsNegativeInfinity($v)) { return '-Infinity' }
            if ([double]::IsNaN($v)) { return 'NaN' }
            return ([double]$v).ToString('R', [cultureinfo]::InvariantCulture)
        }
        if ($v -is [decimal]) { return ([decimal]$v).ToString([cultureinfo]::InvariantCulture) }
        return ([string]$v)
    }

    #endregion

    #region script and blocks

    #the whole file: a module exporting the script as a script block registered at its virtual path
    [string] CompileFile([ScriptBlockAst]$ast, [string]$runtimeImport) {
        $this.Out = [System.Text.StringBuilder]::new()
        $this.Line("//Generated by Web/Convert-AzCmplyToWeb.ps1 from $($this.SourceName). Do not edit; run the generator instead.")
        $this.Line("import { R } from $([PsToJs]::Q($runtimeImport));")
        $this.Line("const F = R.file($([PsToJs]::Q($this.SourceName)));")
        $meta = $this.ParamMeta($ast.ParamBlock, $null, $ast)
        $this.Line("export default R.script($([PsToJs]::Q($this.VirtualPath)), $meta, (S, O) => {")
        $this.Indent++
        $this.CompileBlockBody($ast)
        $this.Indent--
        $this.Line('});')
        return $this.Out.ToString()
    }

    [void] CompileBlockBody([ScriptBlockAst]$ast) {
        if ($ast.BeginBlock -or $ast.ProcessBlock -or $ast.DynamicParamBlock) { $this.Fail($ast, 'begin, process and dynamicparam blocks are not supported') }
        $frame = [JsFrame]::new()
        if ($ast.ParamBlock) {
            foreach ($p in $ast.ParamBlock.Parameters) {
                $type = $this.ParameterType($p)
                if ($type -and $type -notin 'switch', 'System.Management.Automation.SwitchParameter') { $frame.Typed[$p.Name.VariablePath.UserPath.ToLowerInvariant()] = $type }
            }
        }
        $this.Frames.Push($frame)
        if ($ast.EndBlock) {
            foreach ($trap in @($ast.EndBlock.Traps)) { if ($trap) { $this.Fail($trap, 'trap is not supported') } }
            foreach ($statement in $ast.EndBlock.Statements) { $this.CompileStatement($statement) }
        }
        [void]$this.Frames.Pop()
    }

    #a script block or function body as an arrow function (S, O) => { ... }
    [string] CompileBodyFunction([ScriptBlockAst]$ast) {
        $saved = $this.Out
        $savedIndent = $this.Indent
        $this.Out = [System.Text.StringBuilder]::new()
        $this.Indent = $savedIndent + 1
        $this.CompileBlockBody($ast)
        $body = $this.Out.ToString()
        $this.Out = $saved
        $this.Indent = $savedIndent
        return "(S, O) => {`n$body$(' ' * (4 * $savedIndent))}"
    }

    [string] ParameterType([ParameterAst]$p) {
        foreach ($attribute in $p.Attributes) {
            if ($attribute -is [TypeConstraintAst]) { return $attribute.TypeName.FullName }
        }
        return $null
    }

    #parameter metadata consumed by the runtime binder
    [string] ParamMeta([ParamBlockAst]$block, [ParameterAst[]]$functionParameters, [Ast]$owner) {
        $parameters = @()
        $advanced = $false
        if ($block) {
            $parameters = @($block.Parameters)
            foreach ($attribute in $block.Attributes) { if ($attribute.TypeName.Name -eq 'CmdletBinding') { $advanced = $true } }
        }
        if ($functionParameters) {
            if ($block -and $block.Parameters.Count) { $this.Fail($owner, 'a function cannot have both a param block and inline parameters') }
            $parameters = @($functionParameters)
        }
        $items = [System.Collections.Generic.List[string]]::new()
        foreach ($p in $parameters) {
            $name = $p.Name.VariablePath.UserPath
            $type = $null
            $isSwitch = $false
            $position = 'null'
            $mandatory = $false
            $aliases = @()
            $validateSet = $null
            $validatePattern = $null
            $allowNull = $false
            $allowEmpty = $false
            foreach ($attribute in $p.Attributes) {
                if ($attribute -is [TypeConstraintAst]) {
                    $type = $attribute.TypeName.FullName
                    if ($type -in 'switch', 'System.Management.Automation.SwitchParameter') { $isSwitch = $true; $type = $null }
                    continue
                }
                switch ($attribute.TypeName.Name) {
                    'Parameter' {
                        $advanced = $true
                        foreach ($named in $attribute.NamedArguments) {
                            $value = if ($named.ExpressionOmitted) { $true } else { $named.Argument.SafeGetValue() }
                            switch ($named.ArgumentName) {
                                'Mandatory' { $mandatory = [bool]$value }
                                'Position' { $position = [string][int]$value }
                                'ValueFromPipeline' { if ($value) { $this.Fail($p, 'ValueFromPipeline parameters are not supported') } }
                                'ValueFromPipelineByPropertyName' { if ($value) { $this.Fail($p, 'ValueFromPipelineByPropertyName parameters are not supported') } }
                                'ValueFromRemainingArguments' { if ($value) { $this.Fail($p, 'ValueFromRemainingArguments parameters are not supported') } }
                                default { }
                            }
                        }
                    }
                    'Alias' { $aliases = @($attribute.PositionalArguments | ForEach-Object { ([string]$_.SafeGetValue()).ToLowerInvariant() }) }
                    'ValidateSet' { $validateSet = @($attribute.PositionalArguments | ForEach-Object { [string]$_.SafeGetValue() }) }
                    'ValidatePattern' { $validatePattern = [string]$attribute.PositionalArguments[0].SafeGetValue() }
                    'AllowNull' { $allowNull = $true }
                    'AllowEmptyString' { $allowEmpty = $true }
                    'AllowEmptyCollection' { $allowEmpty = $true }
                    'ValidateRange' { }
                    'ValidateNotNullOrEmpty' { }
                    'ValidateNotNull' { }
                    'SupportsWildcards' { }
                    default { $this.Fail($attribute, "parameter attribute [$($attribute.TypeName.Name)] is not supported") }
                }
            }
            $parts = [System.Collections.Generic.List[string]]::new()
            $parts.Add("n: $([PsToJs]::Q($name))")
            $parts.Add("t: $(if ($type) { [PsToJs]::Q($type) } else { 'null' })")
            if ($isSwitch) { $parts.Add('sw: 1') }
            $parts.Add("pos: $position")
            if ($mandatory) { $parts.Add('mand: 1') }
            if ($allowNull) { $parts.Add('allowNull: 1') }
            if ($allowEmpty) { $parts.Add('allowEmpty: 1') }
            if ($aliases.Count) { $parts.Add("al: [$(($aliases | ForEach-Object { [PsToJs]::Q($_) }) -join ', ')]") }
            if ($validateSet) { $parts.Add("vs: [$(($validateSet | ForEach-Object { [PsToJs]::Q($_) }) -join ', ')]") }
            if ($validatePattern) { $parts.Add("vp: $([PsToJs]::Q($validatePattern))") }
            if ($p.DefaultValue) {
                $this.Frames.Push([JsFrame]::new())
                $default = $this.Expr($p.DefaultValue)
                [void]$this.Frames.Pop()
                $parts.Add("def: S => $default")
            }
            $items.Add("{ $($parts -join ', ') }")
        }
        return "{ params: [$($items -join ', ')], adv: $(if ($advanced) { 1 } else { 0 }) }"
    }

    #endregion

    #region statements

    [void] Position([Ast]$ast) {
        $this.Line("R.ln = F + $($ast.Extent.StartLineNumber);")
    }

    [void] CompileStatements([StatementBlockAst]$block) {
        if ($null -eq $block) { return }
        foreach ($trap in @($block.Traps)) { if ($trap) { $this.Fail($trap, 'trap is not supported') } }
        foreach ($statement in $block.Statements) { $this.CompileStatement($statement) }
    }

    [void] Block([StatementBlockAst]$block) {
        $this.Indent++
        $this.CompileStatements($block)
        $this.Indent--
    }

    [void] CompileStatement([StatementAst]$ast) {
        $outName = $this.Frame().Out
        switch ($ast.GetType().Name) {
            'PipelineAst' {
                $this.Position($ast)
                $this.CompilePipelineStatement($ast, $outName)
            }
            'CommandExpressionAst' {
                $this.Position($ast)
                $this.CompilePipelineStatement($ast, $outName)
            }
            'AssignmentStatementAst' {
                $this.Position($ast)
                $this.CompileAssignment($ast)
            }
            'IfStatementAst' { $this.CompileIf($ast) }
            'ForEachStatementAst' { $this.CompileForEach($ast) }
            'ForStatementAst' { $this.CompileFor($ast) }
            'WhileStatementAst' {
                $this.Position($ast)
                $this.Line("while ($($this.Condition($ast.Condition))) {")
                $this.LoopBlock($ast.Body)
                $this.Line('}')
            }
            'DoWhileStatementAst' {
                $this.Position($ast)
                $this.Line('do {')
                $this.LoopBlock($ast.Body)
                $this.Line("} while ($($this.Condition($ast.Condition)));")
            }
            'DoUntilStatementAst' {
                $this.Position($ast)
                $this.Line('do {')
                $this.LoopBlock($ast.Body)
                $this.Line("} while (!($($this.Condition($ast.Condition))));")
            }
            'SwitchStatementAst' { $this.CompileSwitch($ast, $outName) }
            'TryStatementAst' { $this.CompileTry($ast) }
            'ThrowStatementAst' {
                $this.Position($ast)
                if ($ast.Pipeline) { $this.Line("throw R.th($($this.PipelineValue($ast.Pipeline)));") }
                else { $this.Line('throw R.th(S["_"] ?? null);') }
            }
            'ReturnStatementAst' {
                $this.Position($ast)
                if ($this.Frame().InValueBlock) { $this.Fail($ast, 'return inside an expression block is not supported') }
                if ($ast.Pipeline) { $this.CompilePipelineStatement($ast.Pipeline, $outName) }
                $this.Line('return;')
            }
            'BreakStatementAst' {
                if ($ast.Label) { $this.Fail($ast, 'labelled break is not supported') }
                if ($this.Frame().LoopDepth -lt 1) { $this.Fail($ast, 'break outside a loop or switch in this block is not supported') }
                $this.Line('break;')
            }
            'ContinueStatementAst' {
                if ($ast.Label) { $this.Fail($ast, 'labelled continue is not supported') }
                if ($this.Frame().LoopDepth -lt 1) { $this.Fail($ast, 'continue outside a loop or switch in this block is not supported') }
                $this.Line('continue;')
            }
            'FunctionDefinitionAst' { $this.CompileFunction($ast) }
            'StatementBlockAst' {
                $this.Line('{')
                $this.Block($ast)
                $this.Line('}')
            }
            default { $this.Fail($ast, "statement type $($ast.GetType().Name) is not supported") }
        }
    }

    #a loop body: break and continue are allowed in it
    [void] LoopBlock([StatementBlockAst]$body) {
        $this.Frame().LoopDepth++
        $this.Block($body)
        $this.Frame().LoopDepth--
    }

    [void] CompileFunction([FunctionDefinitionAst]$ast) {
        $this.Position($ast)
        if ($ast.IsFilter -or $ast.IsWorkflow) { $this.Fail($ast, 'filters and workflows are not supported') }
        $meta = $this.ParamMeta($ast.Body.ParamBlock, $ast.Parameters, $ast)
        $hash = $this.FunctionHash($ast)
        $meta = $meta.Substring(0, $meta.Length - 2) + ", h: $([PsToJs]::Q($hash)) }"
        $typedExtra = @{}
        if ($ast.Parameters) {
            foreach ($p in $ast.Parameters) { $t = $this.ParameterType($p); if ($t -and $t -ne 'switch') { $typedExtra[$p.Name.VariablePath.UserPath.ToLowerInvariant()] = $t } }
        }
        $body = $this.CompileFunctionBody($ast.Body, $typedExtra)
        $this.Line("R.def(S, $([PsToJs]::Q($ast.Name)), $meta, $body);")
    }

    [string] FunctionHash([FunctionDefinitionAst]$ast) {
        $text = $ast.Extent.Text -replace "`r`n", "`n"
        $bytes = [System.Security.Cryptography.SHA256]::HashData([System.Text.Encoding]::UTF8.GetBytes($text))
        return [Convert]::ToHexString($bytes, 0, 8).ToLowerInvariant()
    }

    [string] CompileFunctionBody([ScriptBlockAst]$ast, [hashtable]$typedExtra) {
        $saved = $this.Out
        $savedIndent = $this.Indent
        $this.Out = [System.Text.StringBuilder]::new()
        $this.Indent = $savedIndent + 1
        if ($ast.BeginBlock -or $ast.ProcessBlock -or $ast.DynamicParamBlock) { $this.Fail($ast, 'begin, process and dynamicparam blocks are not supported') }
        $frame = [JsFrame]::new()
        foreach ($key in $typedExtra.Keys) { $frame.Typed[$key] = $typedExtra[$key] }
        if ($ast.ParamBlock) {
            foreach ($p in $ast.ParamBlock.Parameters) {
                $type = $this.ParameterType($p)
                if ($type -and $type -notin 'switch', 'System.Management.Automation.SwitchParameter') { $frame.Typed[$p.Name.VariablePath.UserPath.ToLowerInvariant()] = $type }
            }
        }
        $this.Frames.Push($frame)
        if ($ast.EndBlock) { foreach ($statement in $ast.EndBlock.Statements) { $this.CompileStatement($statement) } }
        [void]$this.Frames.Pop()
        $body = $this.Out.ToString()
        $this.Out = $saved
        $this.Indent = $savedIndent
        return "(S, O) => {`n$body$(' ' * (4 * $savedIndent))}"
    }

    [void] CompileIf([IfStatementAst]$ast) {
        $this.Position($ast)
        $first = $true
        foreach ($clause in $ast.Clauses) {
            $condition = $this.Condition($clause.Item1)
            if ($first) { $this.Line("if ($condition) {") } else { $this.Line("} else if ($condition) {") }
            $first = $false
            $this.Block($clause.Item2)
        }
        if ($ast.ElseClause) {
            $this.Line('} else {')
            $this.Block($ast.ElseClause)
        }
        $this.Line('}')
    }

    [void] CompileForEach([ForEachStatementAst]$ast) {
        $this.Position($ast)
        if ($ast.Flags -ne 'None') { $this.Fail($ast, 'foreach -parallel is not supported') }
        $item = $this.Tmp('it')
        $source = $this.ForEachSource($ast.Condition)
        $this.Line("for (const $item of $source) {")
        $this.Indent++
        $this.Line("$($this.VariableTarget($ast.Variable)) = $item;")
        $this.Indent--
        $this.LoopBlock($ast.Body)
        $this.Line('}')
    }

    [string] ForEachSource([PipelineBaseAst]$pipeline) {
        $expression = $this.PureExpression($pipeline)
        if ($expression) { return "R.fi($($this.Expr($expression)))" }
        return "R.fi(R.u($($this.PipelineItems($pipeline))))"
    }

    [void] CompileFor([ForStatementAst]$ast) {
        $this.Position($ast)
        $init = if ($ast.Initializer) { $this.InlineStatement($ast.Initializer) } else { '' }
        $condition = if ($ast.Condition) { $this.Condition($ast.Condition) } else { 'true' }
        $iterator = if ($ast.Iterator) { $this.InlineStatement($ast.Iterator) } else { '' }
        $this.Line("for ($init; $condition; $iterator) {")
        $this.LoopBlock($ast.Body)
        $this.Line('}')
    }

    #an assignment or increment as a JS expression, for for-loop headers
    [string] InlineStatement([PipelineBaseAst]$ast) {
        if ($ast -is [AssignmentStatementAst]) { return $this.AssignmentExpression($ast) }
        $expression = $this.PureExpression($ast)
        if ($expression) { return $this.Expr($expression) }
        $this.Fail($ast, 'only assignments and expressions are supported in a for statement header')
        return ''
    }

    [void] CompileSwitch([SwitchStatementAst]$ast, [string]$outName) {
        $this.Position($ast)
        if ($ast.Label) { $this.Fail($ast, 'labelled switch is not supported') }
        $flags = [string]$ast.Flags
        if ($flags -match 'File') { $this.Fail($ast, 'switch -File is not supported') }
        $regex = $flags -match 'Regex'
        $wildcard = $flags -match 'Wildcard'
        $caseSensitive = $flags -match 'CaseSensitive'
        $item = $this.Tmp('sw')
        $matched = $this.Tmp('hit')
        $saved = $this.Tmp('prev')
        $had = $this.Tmp('had')
        $source = $this.PureExpression($ast.Condition)
        $sourceJs = if ($source) { "R.pi($($this.Expr($source)))" } else { $this.PipelineItems($ast.Condition) }
        $this.Line("const $had = Object.prototype.hasOwnProperty.call(S, '_'), $saved = S['_'];")
        $this.Line('try {')
        $this.Indent++
        $this.Line("for (const $item of $sourceJs) {")
        $this.Indent++
        $this.Line("S['_'] = $item;")
        $this.Line("let $matched = false;")
        $this.Indent--
        $this.Frame().LoopDepth++
        foreach ($clause in $ast.Clauses) {
            $test = $this.SwitchTest($clause.Item1, $item, $regex, $wildcard, $caseSensitive)
            $this.Indent++
            $this.Line("if ($test) {")
            $this.Indent++
            $this.Line("$matched = true;")
            $this.Indent--
            $this.Block($clause.Item2)
            $this.Line('}')
            $this.Indent--
        }
        if ($ast.Default) {
            $this.Indent++
            $this.Line("if (!$matched) {")
            $this.Block($ast.Default)
            $this.Line('}')
            $this.Indent--
        }
        $this.Frame().LoopDepth--
        $this.Line('}')
        $this.Indent--
        $this.Line("} finally { if ($had) { S['_'] = $saved; } else { delete S['_']; } }")
    }

    [string] SwitchTest([ExpressionAst]$condition, [string]$item, [bool]$regex, [bool]$wildcard, [bool]$caseSensitive) {
        if ($condition -is [ScriptBlockExpressionAst]) {
            return "R.t(R.u(R.runItem($($this.Expr($condition)), S, $item)))"
        }
        $value = if ($condition -is [StringConstantExpressionAst]) { [PsToJs]::Q($condition.Value) } else { $this.Expr($condition) }
        $c = if ($caseSensitive) { 'true' } else { 'false' }
        if ($regex) { return "R.t(R.match(S, $item, $value, $c))" }
        if ($wildcard) { return "R.t(R.like($item, $value, $c))" }
        return "R.t(R.eq($item, $value, $c))"
    }

    [void] CompileTry([TryStatementAst]$ast) {
        $this.Position($ast)
        $this.Line('try {')
        $this.Block($ast.Body)
        if ($ast.CatchClauses.Count -gt 1) { $this.Fail($ast, 'more than one catch clause is not supported') }
        if ($ast.CatchClauses.Count -eq 1) {
            $clause = $ast.CatchClauses[0]
            if ($clause.CatchTypes.Count) { $this.Fail($clause, 'typed catch clauses are not supported') }
            $e = $this.Tmp('err')
            $this.Line("} catch ($e) {")
            $this.Indent++
            $this.Line("S['_'] = R.er($e);")
            $this.Indent--
            $this.Block($clause.Body)
        }
        if ($ast.Finally) {
            $this.Line('} finally {')
            $this.Block($ast.Finally)
        }
        $this.Line('}')
    }

    #endregion

    #region pipelines

    #a statement that produces a value: a pipeline, an assignment or a bare command expression
    static [bool] IsValueStatement([StatementAst]$statement) {
        return ($statement -is [PipelineBaseAst] -or $statement -is [CommandExpressionAst])
    }

    #the single expression of a pipeline without commands, or $null
    [ExpressionAst] PureExpression([StatementAst]$pipeline) {
        if ($pipeline -is [CommandExpressionAst] -and -not $pipeline.Redirections.Count) { return $pipeline.Expression }
        if ($pipeline -is [PipelineAst] -and $pipeline.PipelineElements.Count -eq 1 -and $pipeline.PipelineElements[0] -is [CommandExpressionAst] -and -not $pipeline.PipelineElements[0].Redirections.Count) {
            return $pipeline.PipelineElements[0].Expression
        }
        return $null
    }

    [void] CompilePipelineStatement([StatementAst]$pipeline, [string]$outName) {
        if ($pipeline -is [AssignmentStatementAst]) { $this.CompileAssignment($pipeline); return }
        if ($pipeline -isnot [PipelineAst] -and $pipeline -isnot [CommandExpressionAst]) { $this.Fail($pipeline, "$($pipeline.GetType().Name) is not supported") }
        $expression = $this.PureExpression($pipeline)
        if ($expression) {
            if ($this.IsVoidExpression($expression)) { $this.Line("$($this.Expr($expression));"); return }
            if ($expression -is [UnaryExpressionAst] -and $expression.TokenKind -in 'PostfixPlusPlus', 'PostfixMinusMinus', 'PlusPlus', 'MinusMinus') {
                $this.Line("$($this.Expr($expression));")
                return
            }
            $this.Line("R.e($outName, $($this.Expr($expression)));")
            return
        }
        $this.Line("R.pa($outName, $($this.PipelineItems($pipeline)));")
    }

    [bool] IsVoidExpression([ExpressionAst]$expression) {
        return ($expression -is [ConvertExpressionAst] -and $expression.Type.TypeName.Name -eq 'void')
    }

    #JS expression for the output items (an array) of a pipeline
    [string] PipelineItems([StatementAst]$pipeline) {
        if ($pipeline -is [AssignmentStatementAst]) { $this.Fail($pipeline, 'an assignment is not supported here') }
        if ($pipeline -is [CommandExpressionAst]) {
            $items = "R.pi($($this.Expr($pipeline.Expression)))"
            if ($pipeline.Redirections.Count) { $items = $this.Redirect($pipeline, $items) }
            return $items
        }
        if ($pipeline -isnot [PipelineAst]) { $this.Fail($pipeline, "$($pipeline.GetType().Name) is not supported") }
        $current = $null
        $index = 0
        foreach ($element in $pipeline.PipelineElements) {
            if ($element -is [CommandExpressionAst]) {
                if ($index -gt 0) { $this.Fail($element, 'an expression can only be the first element of a pipeline') }
                $current = "R.pi($($this.Expr($element.Expression)))"
                if ($element.Redirections.Count) { $current = $this.Redirect($element, $current) }
            } else {
                $current = $this.Command($element, $(if ($index -eq 0) { 'null' } else { $current }))
            }
            $index++
        }
        return $current
    }

    [string] Redirect([CommandBaseAst]$element, [string]$js) {
        $quiet = $false
        foreach ($redirection in $element.Redirections) {
            if ($redirection -isnot [FileRedirectionAst] -or $redirection.Location.Extent.Text -ne '$null') { $this.Fail($redirection, 'only redirection to $null is supported') }
            switch ([string]$redirection.FromStream) {
                'Output' { $this.Fail($redirection, 'redirecting output to $null is not supported, use $null = or [void]') }
                'Error' { }
                default { $quiet = $true }
            }
        }
        if ($quiet) { return "R.quiet(() => $js)" }
        return $js
    }

    [string] Command([CommandAst]$ast, [string]$inputJs) {
        $elements = $ast.CommandElements
        $argumentsJs = $this.CommandArguments($ast, 1)
        $dot = $ast.InvocationOperator -eq 'Dot'
        $name = $ast.GetCommandName()
        $js = $null
        if ($ast.InvocationOperator -eq 'Unknown' -and $name) {
            if (-not $this.KnownCommands.Contains($name) -and $name -notin [PsToJs]::RuntimeCmdlets) {
                $this.Fail($ast, "command '$name' is not defined in the converted scripts and not implemented by the runtime")
            }
            [void]$this.UsedCommands.Add($name)
            $js = "R.cmd(S, $([PsToJs]::Q($name)), $argumentsJs, $inputJs)"
        } else {
            $target = $elements[0]
            $targetJs = if ($target -is [StringConstantExpressionAst] -and $target.StringConstantType -eq 'BareWord') { [PsToJs]::Q($target.Value) } else { $this.Expr($target) }
            $js = "R.inv(S, $targetJs, $argumentsJs, $inputJs, $(if ($dot) { 'true' } else { 'false' }))"
        }
        if ($ast.Redirections.Count) { $js = $this.Redirect($ast, $js) }
        return $js
    }

    [string] CommandArguments([CommandAst]$ast, [int]$start) {
        $items = [System.Collections.Generic.List[string]]::new()
        $elements = $ast.CommandElements
        for ($i = $start; $i -lt $elements.Count; $i++) {
            $element = $elements[$i]
            if ($element -is [CommandParameterAst]) {
                if ($element.Argument) { $items.Add("R.np($([PsToJs]::Q($element.ParameterName)), $($this.Expr($element.Argument)))") }
                else { $items.Add("R.np($([PsToJs]::Q($element.ParameterName)))") }
                continue
            }
            if ($element -is [VariableExpressionAst] -and $element.Splatted) { $this.Fail($element, 'splatting is not supported') }
            $items.Add($this.Expr($element))
        }
        return "[$($items -join ', ')]"
    }

    #value of a pipeline used as an expression: the expression itself, or the unwrapped command output
    [string] PipelineValue([StatementAst]$pipeline) {
        if ($pipeline -is [AssignmentStatementAst]) { return "($($this.AssignmentExpression($pipeline)))" }
        $expression = $this.PureExpression($pipeline)
        if ($expression) { return $this.Expr($expression) }
        return "R.u($($this.PipelineItems($pipeline)))"
    }

    [string] Condition([StatementAst]$pipeline) {
        $expression = $this.PureExpression($pipeline)
        if ($expression) { return $this.BoolExpr($expression) }
        return "R.t($($this.PipelineValue($pipeline)))"
    }

    #an expression as a JS boolean, without a truthiness call where the operator already yields one
    [string] BoolExpr([ExpressionAst]$expression) {
        if ($expression -is [UnaryExpressionAst] -and $expression.TokenKind -in 'Not', 'Exclaim') { return "!$($this.BoolExpr($expression.Child))" }
        if ($expression -is [BinaryExpressionAst]) {
            switch ([string]$expression.Operator) {
                'And' { return "($($this.BoolExpr($expression.Left)) && $($this.BoolExpr($expression.Right)))" }
                'Or' { return "($($this.BoolExpr($expression.Left)) || $($this.BoolExpr($expression.Right)))" }
                default { }
            }
        }
        if ($expression -is [ParenExpressionAst]) {
            $inner = $this.PureExpression($expression.Pipeline)
            if ($inner) { return $this.BoolExpr($inner) }
        }
        return "R.t($($this.Expr($expression)))"
    }

    #value of a statement used as a value (if, switch, foreach, try ...): collected into a temporary array
    [string] StatementValueInline([StatementAst]$statement) {
        if ([PsToJs]::IsValueStatement($statement)) { return $this.PipelineValue($statement) }
        $temp = $this.Tmp('v')
        $saved = $this.Out
        $savedIndent = $this.Indent
        $this.Out = [System.Text.StringBuilder]::new()
        $this.Indent = $savedIndent + 1
        $frame = [JsFrame]::new()
        $frame.Out = $temp
        $frame.InValueBlock = $true
        foreach ($key in $this.Frame().Typed.Keys) { $frame.Typed[$key] = $this.Frame().Typed[$key] }
        $this.Frames.Push($frame)
        $this.Line("const $temp = [];")
        $this.CompileStatement($statement)
        $this.Line("return R.u($temp);")
        [void]$this.Frames.Pop()
        $body = $this.Out.ToString()
        $this.Out = $saved
        $this.Indent = $savedIndent
        return "(() => {`n$body$(' ' * (4 * $savedIndent))})()"
    }

    #endregion

    #region assignment

    [void] CompileAssignment([AssignmentStatementAst]$ast) {
        $right = $ast.Right
        $left = $ast.Left
        #a statement on the right (if, switch, foreach ...) writes to a temporary array in place, so break, continue and
        #return keep their meaning
        if (-not [PsToJs]::IsValueStatement($right) -and $ast.Operator -eq 'Equals') {
            $temp = $this.Tmp('v')
            $this.Line("const $temp = [];")
            $savedOut = $this.Frame().Out
            $this.Frame().Out = $temp
            $this.CompileStatement($right)
            $this.Frame().Out = $savedOut
            $this.Line("$($this.AssignTo($left, "R.u($temp)"));")
            return
        }
        if ($left -is [VariableExpressionAst] -and $left.VariablePath.UserPath -eq 'null' -and $ast.Operator -eq 'Equals') {
            $expression = $this.PureExpression($right)
            if ($expression) { $this.Line("$($this.Expr($expression));") } else { $this.Line("$($this.PipelineItems($right));") }
            return
        }
        $this.Line("$($this.AssignmentExpression($ast));")
    }

    [string] AssignmentExpression([AssignmentStatementAst]$ast) {
        $right = $ast.Right
        if (-not [PsToJs]::IsValueStatement($right)) { $this.Fail($ast, 'a statement on the right of this assignment is not supported') }
        $value = $this.PipelineValue($right)
        $left = $ast.Left
        $op = [string]$ast.Operator
        if ($op -eq 'Equals') { return $this.AssignTo($left, $value) }
        $fn = switch ($op) {
            'PlusEquals' { 'R.add' } 'MinusEquals' { 'R.sub' } 'MultiplyEquals' { 'R.mul' } 'DivideEquals' { 'R.div' } 'RemainderEquals' { 'R.mod' }
            default { $null }
        }
        if (-not $fn) { $this.Fail($ast, "assignment operator $op is not supported") }
        if ($left -is [VariableExpressionAst]) {
            $target = $this.VariableTarget($left)
            return $this.TypedAssign($left, $target, "$fn($target ?? null, $value)")
        }
        if ($left -is [MemberExpressionAst]) {
            $obj = $this.Tmp('o')
            $member = $this.MemberName($left)
            return "((($obj) => R.sm($obj, $member, $fn(R.m($obj, $member), $value)))($($this.Expr($left.Expression))))"
        }
        if ($left -is [IndexExpressionAst]) {
            $obj = $this.Tmp('o')
            $key = $this.Tmp('k')
            return "((($obj, $key) => R.si($obj, $key, $fn(R.i($obj, $key), $value)))($($this.Expr($left.Target)), $($this.Expr($left.Index))))"
        }
        $this.Fail($ast, 'unsupported assignment target')
        return ''
    }

    #JS that stores $value into a PowerShell assignment target
    [string] AssignTo([ExpressionAst]$left, [string]$value) {
        if ($left -is [VariableExpressionAst]) {
            if ($left.VariablePath.UserPath -eq 'null') { return $value }
            return $this.TypedAssign($left, $this.VariableTarget($left), $value)
        }
        if ($left -is [ConvertExpressionAst] -and $left.Child -is [VariableExpressionAst]) {
            $type = $left.Type.TypeName.FullName
            $this.Frame().Typed[$left.Child.VariablePath.UserPath.ToLowerInvariant()] = $type
            return "$($this.VariableTarget($left.Child)) = R.c($([PsToJs]::Q($type)), $value)"
        }
        if ($left -is [MemberExpressionAst]) {
            if ($left.Static) { $this.Fail($left, 'assigning a static member is not supported') }
            return "R.sm($($this.Expr($left.Expression)), $($this.MemberName($left)), $value)"
        }
        if ($left -is [IndexExpressionAst]) {
            return "R.si($($this.Expr($left.Target)), $($this.Expr($left.Index)), $value)"
        }
        if ($left -is [ArrayLiteralAst]) {
            $temp = $this.Tmp('m')
            $parts = [System.Collections.Generic.List[string]]::new()
            for ($i = 0; $i -lt $left.Elements.Count; $i++) { $parts.Add($this.AssignTo($left.Elements[$i], "$temp[$i]")) }
            return "((($temp) => { $($parts -join '; '); })(R.mi($value, $($left.Elements.Count))))"
        }
        $this.Fail($left, "assignment to $($left.GetType().Name) is not supported")
        return ''
    }

    [string] TypedAssign([VariableExpressionAst]$variable, [string]$target, [string]$value) {
        $name = $variable.VariablePath.UserPath.ToLowerInvariant()
        $type = $null
        if ($variable.VariablePath.IsUnqualified -or $variable.VariablePath.IsLocal) { $type = $this.Frame().Typed[$name] }
        if ($type) { return "$target = R.c($([PsToJs]::Q($type)), $value)" }
        return "$target = $value"
    }

    #endregion

    #region variables

    [string] VariableTarget([VariableExpressionAst]$ast) {
        $path = $ast.VariablePath
        $name = $path.UserPath
        $lname = $name.ToLowerInvariant()
        if ($path.IsDriveQualified -and -not ($path.IsScript -or $path.IsGlobal -or $path.IsLocal -or $path.IsPrivate)) { $this.Fail($ast, "assigning to $($path.DriveName): is not supported") }
        if ($lname -in 'true', 'false', 'psscriptroot', 'pscommandpath', 'executioncontext', 'psversiontable') { $this.Fail($ast, "cannot assign to automatic variable `$$name") }
        if ($lname -eq 'psitem') { $lname = '_' }
        if ($path.IsScript) { return "R.ss(S)[$([PsToJs]::Q($lname))]" }
        if ($path.IsGlobal) { return "R.G[$([PsToJs]::Q($lname))]" }
        return "S[$([PsToJs]::Q($lname))]"
    }

    [string] VariableRead([VariableExpressionAst]$ast) {
        if ($ast.Splatted) { $this.Fail($ast, 'splatting is not supported') }
        $path = $ast.VariablePath
        $name = $path.UserPath
        $lname = $name.ToLowerInvariant()
        if ($path.DriveName -eq 'env') { return "R.env($([PsToJs]::Q($name)))" }
        if ($path.DriveName -and $path.DriveName -notin 'script', 'global', 'local', 'private') { $this.Fail($ast, "variable drive $($path.DriveName): is not supported") }
        if ($path.IsScript) { return "(R.ss(S)[$([PsToJs]::Q($lname))] ?? null)" }
        if ($path.IsGlobal) { return "(R.G[$([PsToJs]::Q($lname))] ?? null)" }
        switch ($lname) {
            'true' { return 'true' }
            'false' { return 'false' }
            'null' { return 'null' }
            'psitem' { return '(S["_"] ?? null)' }
            '_' { return '(S["_"] ?? null)' }
            'args' { return '(S["args"] ?? [])' }
            'psscriptroot' { return [PsToJs]::Q($this.VirtualRoot) }
            'pscommandpath' { return [PsToJs]::Q($this.VirtualPath) }
            'executioncontext' { return 'R.ctx' }
            'psversiontable' { return 'R.psv' }
            'iswindows' { return 'true' }
            'islinux' { return 'false' }
            'ismacos' { return 'false' }
            'iscoreclr' { return 'true' }
            default { }
        }
        if ($name -in [PsToJs]::UnsupportedVariables) { $this.Fail($ast, "automatic variable `$$name is not supported") }
        return "(S[$([PsToJs]::Q($lname))] ?? null)"
    }

    #endregion

    #region expressions

    [string] Expr([Ast]$ast) {
        switch ($ast.GetType().Name) {
            'StringConstantExpressionAst' { return [PsToJs]::Q($ast.Value) }
            'ConstantExpressionAst' {
                if ($null -eq $ast.Value) { return 'null' }
                if ($ast.Value -is [bool]) { return $(if ($ast.Value) { 'true' } else { 'false' }) }
                if ($ast.Value -is [string]) { return [PsToJs]::Q($ast.Value) }
                if ($ast.Value -is [char]) { return [PsToJs]::Q([string]$ast.Value) }
                return [PsToJs]::Num($ast.Value)
            }
            'ExpandableStringExpressionAst' { return $this.ExpandableString($ast) }
            'VariableExpressionAst' { return $this.VariableRead($ast) }
            'MemberExpressionAst' {
                if ($ast.Static) { return "R.st($([PsToJs]::Q($ast.Expression.TypeName.FullName)), $($this.MemberName($ast)))" }
                return "R.m($($this.Expr($ast.Expression)), $($this.MemberName($ast)))"
            }
            'InvokeMemberExpressionAst' {
                $arguments = @(foreach ($argument in @($ast.Arguments)) { if ($argument) { $this.Expr($argument) } })
                if ($ast.Static) { return "R.sc($([PsToJs]::Q($ast.Expression.TypeName.FullName)), $($this.MemberName($ast)), [$($arguments -join ', ')])" }
                return "R.im($($this.Expr($ast.Expression)), $($this.MemberName($ast)), [$($arguments -join ', ')])"
            }
            'IndexExpressionAst' { return "R.i($($this.Expr($ast.Target)), $($this.Expr($ast.Index)))" }
            'ArrayLiteralAst' { return "[$((@($ast.Elements | ForEach-Object { "R.v($($this.Expr($_)))" })) -join ', ')]" }
            'ArrayExpressionAst' { return $this.ArrayExpression($ast) }
            'SubExpressionAst' { return $this.SubExpression($ast) }
            'ParenExpressionAst' {
                $inner = $ast.Pipeline
                $expression = $this.PureExpression($inner)
                if ($expression) { return "($($this.Expr($expression)))" }
                return $this.PipelineValue($inner)
            }
            'HashtableAst' { return $this.Hashtable($ast, $false) }
            'ScriptBlockExpressionAst' { return $this.ScriptBlockLiteral($ast.ScriptBlock) }
            'ConvertExpressionAst' { return $this.Convert($ast) }
            'TypeExpressionAst' { return "R.ty($([PsToJs]::Q($ast.TypeName.FullName)))" }
            'BinaryExpressionAst' { return $this.Binary($ast) }
            'UnaryExpressionAst' { return $this.Unary($ast) }
            'TernaryExpressionAst' { return "($($this.BoolExpr($ast.Condition)) ? $($this.Expr($ast.IfTrue)) : $($this.Expr($ast.IfFalse)))" }
            'CommandExpressionAst' { return $this.Expr($ast.Expression) }
            'AttributedExpressionAst' { $this.Fail($ast, 'attributed expressions are not supported') }
            'UsingExpressionAst' { $this.Fail($ast, '$using: is not supported') }
            default { $this.Fail($ast, "expression type $($ast.GetType().Name) is not supported") }
        }
        return ''
    }

    [string] MemberName([MemberExpressionAst]$ast) {
        if ($ast.NullConditional) { }
        if ($ast.Member -is [StringConstantExpressionAst]) { return [PsToJs]::Q($ast.Member.Value) }
        return "R.str($($this.Expr($ast.Member)))"
    }

    [string] ArrayExpression([ArrayExpressionAst]$ast) {
        $statements = $ast.SubExpression.Statements
        if ($statements.Count -eq 0) { return '[]' }
        if ($statements.Count -eq 1 -and $statements[0] -is [PipelineAst]) {
            $expression = $this.PureExpression($statements[0])
            if ($expression) { return "R.a($($this.Expr($expression)))" }
            return $this.PipelineItems($statements[0])
        }
        return $this.CollectStatements($ast.SubExpression, $false)
    }

    [string] SubExpression([SubExpressionAst]$ast) {
        $statements = $ast.SubExpression.Statements
        if ($statements.Count -eq 0) { return 'R.u([])' }
        if ($statements.Count -eq 1 -and $statements[0] -is [PipelineAst]) {
            $expression = $this.PureExpression($statements[0])
            if ($expression) { return "R.u(R.pi($($this.Expr($expression))))" }
            return "R.u($($this.PipelineItems($statements[0])))"
        }
        return $this.CollectStatements($ast.SubExpression, $true)
    }

    #statements inside $( ) or @( ): run in place, output collected
    [string] CollectStatements([StatementBlockAst]$block, [bool]$unwrap) {
        $temp = $this.Tmp('v')
        $saved = $this.Out
        $savedIndent = $this.Indent
        $this.Out = [System.Text.StringBuilder]::new()
        $this.Indent = $savedIndent + 1
        $frame = [JsFrame]::new()
        $frame.Out = $temp
        $frame.InValueBlock = $true
        foreach ($key in $this.Frame().Typed.Keys) { $frame.Typed[$key] = $this.Frame().Typed[$key] }
        $this.Frames.Push($frame)
        $this.Line("const $temp = [];")
        $this.CompileStatements($block)
        $this.Line($(if ($unwrap) { "return R.u($temp);" } else { "return $temp;" }))
        [void]$this.Frames.Pop()
        $body = $this.Out.ToString()
        $this.Out = $saved
        $this.Indent = $savedIndent
        return "(() => {`n$body$(' ' * (4 * $savedIndent))})()"
    }

    [string] Hashtable([HashtableAst]$ast, [bool]$ordered) {
        $parts = [System.Collections.Generic.List[string]]::new()
        foreach ($pair in $ast.KeyValuePairs) {
            $key = if ($pair.Item1 -is [StringConstantExpressionAst]) { [PsToJs]::Q($pair.Item1.Value) } else { $this.Expr($pair.Item1) }
            $parts.Add($key)
            $parts.Add($this.StatementValueInline($pair.Item2))
        }
        return "R.ht([$($parts -join ', ')], $(if ($ordered) { 'true' } else { 'false' }))"
    }

    [string] ScriptBlockLiteral([ScriptBlockAst]$ast) {
        $meta = $this.ParamMeta($ast.ParamBlock, $null, $ast)
        $text = $ast.Extent.Text
        if ($text.StartsWith('{') -and $text.EndsWith('}')) { $text = $text.Substring(1, $text.Length - 2) }
        $meta = $meta.Substring(0, $meta.Length - 2) + ", text: $([PsToJs]::Q($text)) }"
        $body = $this.CompileBodyFunction($ast)
        return "R.sb($meta, $body)"
    }

    [string] Convert([ConvertExpressionAst]$ast) {
        $type = $ast.Type.TypeName.FullName
        $name = $ast.Type.TypeName.Name
        switch ($name) {
            'ordered' {
                if ($ast.Child -isnot [HashtableAst]) { $this.Fail($ast, '[ordered] needs a hashtable literal') }
                return $this.Hashtable($ast.Child, $true)
            }
            'void' { return "void ($($this.Expr($ast.Child)))" }
            'ref' {
                if ($ast.Child -isnot [VariableExpressionAst]) { $this.Fail($ast, '[ref] is only supported on a variable') }
                $target = $this.VariableTarget($ast.Child)
                $read = $this.VariableRead($ast.Child)
                return "R.ref(() => $read, x => { $target = x; })"
            }
            default { }
        }
        if ($name -in 'pscustomobject', 'psobject', 'System.Management.Automation.PSCustomObject' -and $ast.Child -is [HashtableAst]) {
            $parts = [System.Collections.Generic.List[string]]::new()
            foreach ($pair in $ast.Child.KeyValuePairs) {
                $key = if ($pair.Item1 -is [StringConstantExpressionAst]) { [PsToJs]::Q($pair.Item1.Value) } else { $this.Expr($pair.Item1) }
                $parts.Add($key)
                $parts.Add($this.StatementValueInline($pair.Item2))
            }
            return "R.pso([$($parts -join ', ')])"
        }
        return "R.c($([PsToJs]::Q($type)), $($this.Expr($ast.Child)))"
    }

    [string] Binary([BinaryExpressionAst]$ast) {
        $op = [string]$ast.Operator
        switch ($op) {
            'And' { return "($($this.BoolExpr($ast.Left)) && $($this.BoolExpr($ast.Right)))" }
            'Or' { return "($($this.BoolExpr($ast.Left)) || $($this.BoolExpr($ast.Right)))" }
            'Xor' { return "($($this.BoolExpr($ast.Left)) !== $($this.BoolExpr($ast.Right)))" }
            'QuestionQuestion' { return "R.coalesce($($this.Expr($ast.Left)), () => $($this.Expr($ast.Right)))" }
            default { }
        }
        $left = $this.Expr($ast.Left)
        $right = $this.Expr($ast.Right)
        $fn = switch ($op) {
            'Ieq' { 'R.eq' } 'Ine' { 'R.ne' } 'Igt' { 'R.gt' } 'Ige' { 'R.ge' } 'Ilt' { 'R.lt' } 'Ile' { 'R.le' }
            'Ceq' { 'R.ceq' } 'Cne' { 'R.cne' } 'Cgt' { 'R.cgt' } 'Cge' { 'R.cge' } 'Clt' { 'R.clt' } 'Cle' { 'R.cle' }
            'Ilike' { 'R.like' } 'Inotlike' { 'R.nlike' } 'Clike' { 'R.clike' } 'Cnotlike' { 'R.cnlike' }
            'Ireplace' { 'R.rep' } 'Creplace' { 'R.crep' } 'Isplit' { 'R.split' } 'Csplit' { 'R.csplit' } 'Join' { 'R.join' }
            'Iin' { 'R.in' } 'Inotin' { 'R.nin' } 'Cin' { 'R.cin' } 'Cnotin' { 'R.cnin' }
            'Icontains' { 'R.cont' } 'Inotcontains' { 'R.ncont' } 'Ccontains' { 'R.ccont' } 'Cnotcontains' { 'R.cncont' }
            'Is' { 'R.is' } 'IsNot' { 'R.isnot' }
            'Plus' { 'R.add' } 'Minus' { 'R.sub' } 'Multiply' { 'R.mul' } 'Divide' { 'R.div' } 'Rem' { 'R.mod' }
            'Band' { 'R.band' } 'Bor' { 'R.bor' } 'Bxor' { 'R.bxor' } 'Shl' { 'R.shl' } 'Shr' { 'R.shr' }
            'DotDot' { 'R.range' } 'Format' { 'R.fmt' }
            default { $null }
        }
        if ($fn) { return "$fn($left, $right)" }
        switch ($op) {
            'Imatch' { return "R.match(S, $left, $right)" }
            'Inotmatch' { return "R.nmatch(S, $left, $right)" }
            'Cmatch' { return "R.cmatch(S, $left, $right)" }
            'Cnotmatch' { return "R.cnmatch(S, $left, $right)" }
            default { }
        }
        $this.Fail($ast, "operator -$op is not supported")
        return ''
    }

    [string] Unary([UnaryExpressionAst]$ast) {
        $kind = [string]$ast.TokenKind
        switch ($kind) {
            'Not' { return "!$($this.BoolExpr($ast.Child))" }
            'Exclaim' { return "!$($this.BoolExpr($ast.Child))" }
            'Minus' { return "R.neg($($this.Expr($ast.Child)))" }
            'Plus' { return "R.add(0, $($this.Expr($ast.Child)))" }
            'Bnot' { return "R.bnot($($this.Expr($ast.Child)))" }
            'Comma' { return "[R.v($($this.Expr($ast.Child)))]" }
            'Join' { return "R.joinU($($this.Expr($ast.Child)))" }
            'Isplit' { return "R.splitU($($this.Expr($ast.Child)))" }
            'Csplit' { return "R.splitU($($this.Expr($ast.Child)))" }
            default { }
        }
        $delta = if ($kind -in 'PostfixPlusPlus', 'PlusPlus') { 1 } elseif ($kind -in 'PostfixMinusMinus', 'MinusMinus') { -1 } else { 0 }
        if (-not $delta) { $this.Fail($ast, "unary operator $kind is not supported") }
        $post = if ($kind -like 'Postfix*') { 'true' } else { 'false' }
        $child = $ast.Child
        if ($child -is [VariableExpressionAst]) {
            $target = $this.VariableTarget($child)
            if ($target -match '^(.*)\[("[^"]*")\]$') { return "R.incv($($Matches[1]), $($Matches[2]), $delta, $post)" }
        }
        if ($child -is [MemberExpressionAst]) { return "R.incm($($this.Expr($child.Expression)), $($this.MemberName($child)), $delta, $post)" }
        if ($child -is [IndexExpressionAst]) { return "R.inci($($this.Expr($child.Target)), $($this.Expr($child.Index)), $delta, $post)" }
        $this.Fail($ast, 'increment target not supported')
        return ''
    }

    #"text $var $(expr)" rebuilt from the source text, so escapes and here-strings come out exactly as PowerShell reads them
    [string] ExpandableString([ExpandableStringExpressionAst]$ast) {
        $text = $ast.Extent.Text
        $base = $ast.Extent.StartOffset
        $kind = [string]$ast.StringConstantType
        $start = 0
        $end = $text.Length
        switch ($kind) {
            'DoubleQuoted' { $start = 1; $end = $text.Length - 1 }
            'DoubleQuotedHereString' {
                $start = $text.IndexOf("`n") + 1
                $end = $text.LastIndexOf("`n")
                if ($end -gt 0 -and $text[$end - 1] -eq "`r") { $end-- }
            }
            'BareWord' { }
            default { $this.Fail($ast, "string kind $kind is not supported") }
        }
        $nested = @{}
        foreach ($expression in $ast.NestedExpressions) { $nested[$expression.Extent.StartOffset - $base] = $expression }
        $parts = [System.Collections.Generic.List[string]]::new()
        $literal = [System.Text.StringBuilder]::new()
        $i = $start
        while ($i -lt $end) {
            if ($nested.ContainsKey($i)) {
                if ($literal.Length) { $parts.Add([PsToJs]::Q($literal.ToString())); [void]$literal.Clear() }
                $expression = $nested[$i]
                $parts.Add("R.str($($this.Expr($expression)))")
                $i = $expression.Extent.EndOffset - $base
                continue
            }
            $c = $text[$i]
            if ($c -eq '`' -and $i + 1 -lt $end) {
                $n = $text[$i + 1]
                switch -CaseSensitive ($n) {
                    '0' { [void]$literal.Append([char]0) }
                    'a' { [void]$literal.Append([char]7) }
                    'b' { [void]$literal.Append([char]8) }
                    'e' { [void]$literal.Append([char]27) }
                    'f' { [void]$literal.Append([char]12) }
                    'n' { [void]$literal.Append("`n") }
                    'r' { [void]$literal.Append("`r") }
                    't' { [void]$literal.Append("`t") }
                    'v' { [void]$literal.Append([char]11) }
                    'u' {
                        $close = $text.IndexOf('}', $i)
                        $code = [Convert]::ToInt32($text.Substring($i + 3, $close - $i - 3), 16)
                        [void]$literal.Append([char]::ConvertFromUtf32($code))
                        $i = $close - 1
                    }
                    default { [void]$literal.Append($n) }
                }
                $i += 2
                continue
            }
            if ($kind -eq 'DoubleQuoted' -and $c -in '"', [char]0x201C, [char]0x201D, [char]0x201E -and $i + 1 -lt $end -and $text[$i + 1] -in '"', [char]0x201C, [char]0x201D, [char]0x201E) {
                [void]$literal.Append($c)
                $i += 2
                continue
            }
            [void]$literal.Append($c)
            $i++
        }
        if ($literal.Length) { $parts.Add([PsToJs]::Q($literal.ToString())) }
        if (-not $parts.Count) { return '""' }
        if ($parts.Count -eq 1 -and $parts[0].StartsWith('"')) { return $parts[0] }
        if (-not $parts[0].StartsWith('"')) { $parts.Insert(0, '""') }
        return "($($parts -join ' + '))"
    }

    #endregion
}
